version: '3.8'

services:
  # MySQL 서비스
  mysql:
    image: mysql
    container_name: cloud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crud
    ports:
      - "3308:3306"
    networks:
      - cloud_native
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot 백엔드 서비스
  spring-back:
    build:
      context: ./cloud-back
    container_name: spring-boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cloud-mysql:3306/crud
      SPRING_DATASOURCE_USERNAME: cloud-mysql
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - cloud_native

  # React 프론트엔드 서비스
  react-front:
    build:
      context: ./cloud-front
    container_name: react
    ports:
      - "80:80"
    networks:
      - cloud_native

networks:
  cloud_native:
    driver: bridge

volumes:
  mysql-data:
    driver: local
